dirs:
  - .

useGitIgnore: true

modifiedFilesOnly : true

ignorePatterns:
  - pattern: '^#'

  - pattern: '^https://x.com/'
    # "reason": "X.com blocks automated requests from GitHub Actions"
  - pattern: '^https://www.meti.go.jp/.*\.pdf$'
    # "reason": "METI government PDF links often timeout in CI"
  - pattern: '^https://www.jftc.go.jp/'
    # "reason": "JFTC government links often return 403 in CI"
  - pattern: '^%20https://'
    # "reason": "Malformed URLs with spaces at the beginning"
