name: Check Markdown links

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'
          folder-path: '.'
          max-depth: -1
