name: Check Markdown Links

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '**/*.md'

jobs:
  check-links:
    name: Linkspector / Reviewdog
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-annotations
          filter_mode: nofilter
          fail_level: any
          config_file: .github/.linkspector.yml